// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk-vZBDGEnfxsoJ18EhllJZBbxnG3RfIs',
    appId: '1:685453403635:web:eb725d7fe8d7c6ce8d1e86',
    messagingSenderId: '685453403635',
    projectId: 'odk-central-393313',
    authDomain: 'odk-central-393313.firebaseapp.com',
    storageBucket: 'odk-central-393313.appspot.com',
    measurementId: 'G-C4FBE7P0RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4Waboq7zFNfF2LaTlFI83Kujxynl50M',
    appId: '1:685453403635:android:901bb295ea495b788d1e86',
    messagingSenderId: '685453403635',
    projectId: 'odk-central-393313',
    storageBucket: 'odk-central-393313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7GGrDgexNfDX5d2g2_p9kOKxtCX9t7ng',
    appId: '1:685453403635:ios:43e71548f38d608c8d1e86',
    messagingSenderId: '685453403635',
    projectId: 'odk-central-393313',
    storageBucket: 'odk-central-393313.appspot.com',
    androidClientId: '685453403635-gaj7voa6ucbplt46ot2362b43iitebeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveysApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7GGrDgexNfDX5d2g2_p9kOKxtCX9t7ng',
    appId: '1:685453403635:ios:43e71548f38d608c8d1e86',
    messagingSenderId: '685453403635',
    projectId: 'odk-central-393313',
    storageBucket: 'odk-central-393313.appspot.com',
    androidClientId: '685453403635-gaj7voa6ucbplt46ot2362b43iitebeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveysApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk-vZBDGEnfxsoJ18EhllJZBbxnG3RfIs',
    appId: '1:685453403635:web:a7ba1f5eee63993d8d1e86',
    messagingSenderId: '685453403635',
    projectId: 'odk-central-393313',
    authDomain: 'odk-central-393313.firebaseapp.com',
    storageBucket: 'odk-central-393313.appspot.com',
    measurementId: 'G-DZVHB50YV8',
  );
}
