/*
clase para manejar la lista de municipios, departamentos, veredas
*/

class PlacesListJson {

//lista de departamentos
static List<String> departments = [
  'ANTIOQUIA', 
  'ATLÁNTICO', 
  'BOGOTÁ, D,C',
  'BOLÍVAR',
  'BOYACÁ',
  'CALDAS',
  'CAQUETÁ',
  'CAUCA',
  'CESAR',
  'CÓRDOBA',
  'CUNDINAMARCA',
  'CHOCÓ',
  'HUILA',
  'LA GUAJIRA',
  'MAGDALENA',
  'META',
  'NARIÑO',
  'NORTE DE SANTANDER',
  'QUINDIO',
  'RISARALDA',
  'SANTANDER',
  'SUCRE',
  'TOLIMA',
  'VALLE DEL CAUCA',
  'ARAUCA',
  'CASANARE',
  'PUTUMAYO',
  'ARCHIPIÉLAGO DE SAN ANDRÉS',
  'AMAZONAS',
  'GUAINÍA',
  'GUAVIARE',
  'VAUPÉS',
  'VICHADA',
  ];



/*lista de municipios*/
 static Map<String, List<String>> municipalitiesByDepartment = {

  'ANTIOQUIA':[
    'MEDELLÍN','ABEJORRAL','ABRIAQUÍ','ALEJANDRÍA','AMAGÁ','AMALFI','ANDES','ANGELÓPOLIS',
    'ANGOSTURA','ANORÍ','SANTA FÉ DE ANTIOQUIA','ANZÁ','APARTADÓ','ARBOLETES','ARGELIA',
    'BARBOSA','BELMIRA','BELLO','BETANIA','BETULIA','CIUDAD BOLÍVAR','BRICEÑO','BURITICÁ','CÁCERES',
    'CALDAS','CAMPAMENTO','CAÑASGORDAS','CARACOLÍ','CARAMANTA','CAREPA','EL CARMEN DE VIBORAL',
    'CAROLINA','CAUCASIA','CHIGORODÓ','COCORNÁ','CONCEPCIÓN','CONCORDIA','COPACABANA','DABEIBA',
    'DONMATÍAS','EBÉJICO','EL BAGRE','ENTRERRÍOS','ENVIGADO','FREDONIA','FRONTINO','GIRALDO','GIRARDOTA',
    'GÓMEZ PLATA','GRANADA','GUADALUPE','GUARNE','GUATAPÉ','HELICONIA','HISPANIA','ITAGÜÍ','ITUANGO','JARDÍN',
    'JERICÓ','LA CEJA','LA ESTRELLA','LA UNIÓN','LIBORINA','MACEO','MARINILLA','MONTEBELLO','MURINDÓ',
    'MUTATÁ','NARIÑO','NECOCLÍ','NECHÍ','OLAYA','PEÑOL','PEÑOL','PUEBLORRICO','PUEBLORRICO','PUERTO BERRÍO',
    'PUERTO NARE','PUERTO TRIUNFO','REMEDIOS','RETIRO','RIONEGRO','SABANALARGA','SABANETA','SALGAR','SAN ANDRÉS DE CUERQUÍA',
    'SAN CARLOS','SAN FRANCISCO','SAN JOSÉ DE LA MONTAÑA','SAN JUAN DE URABÁ','SAN LUIS',
    'SAN PEDRO DE LOS MILAGROS','SAN PEDRO DE URABÁ',
    'SAN RAFAEL','SAN ROQUE','SAN VICENTE FERRER','SANTA BÁRBARA','SANTA ROSA DE OSOS',
    'SANTO DOMINGO','EL SANTUARIO','SEGOVIA','SONSÓN',
    'SOPETRÁN','TÁMESIS','TARAZÁ','TARSO','TITIRIBÍ','TOLEDO','TURBO','URAMITA','URRAO',
    'VALDIVIA','VALPARAÍSO','VEGACHÍ','VIGÍA DEL FUERTE','YALÍ','YARUMAL','YOLOMBÓ','YONDÓ','ZARAGOZA',
    ], 
  'ATLÁNTICO':[
    'BARRANQUILLA','BARANOA','CAMPO DE LA CRUZ','CANDELARIA','GALAPA','JUAN DE ACOSTA',
    'LURUACO','MALAMBO','MANATÍ','PALMAR DE VARELA','PIOJÓ','POLONUEVO','PONEDERA','PUERTO COLOMBIA',
    'REPELÓN','SABANAGRANDE','SABANALARGA','SANTA LUCÍA','SANTO TOMÁS','SOLEDAD','SUAN','TUBARÁ','USIACURÍ'
  ], 
  'BOGOTÁ, D,C':[
    'BOGOTÁ, D.C.'
  ],
  'BOLÍVAR':[
    'CARTAGENA DE INDIAS','ACHÍ','ALTOS DEL ROSARIO','ARENAL','ARJONA','ARROYOHONDO',
    'BARRANCO DE LOBA','CALAMAR','CANTAGALLO','CICUCO','CÓRDOBA','CLEMENCIA',
    'EL CARMEN DE BOLÍVAR','EL GUAMO','EL PEÑÓN',
    'HATILLO DE LOBA','MAGANGUÉ','MAHATES','MARGARITA',
    'MARÍA LA BAJA','MONTECRISTO','MOMPÓS','NOROSÍ','PINILLOS','REGIDOR',
    'RÍO VIEJO','SAN CRISTÓBAL','SAN FERNANDO','SAN JACINTO','SAN JACINTO DEL CAUCA',
    'SAN PABLO','SANTA CATALINA','SANTA ROSA','SANTA ROSA DEL SUR','SIMITÍ','SOPLAVIENTO',
    'TIQUISIO','TURBACO','TURBANÁ','VILLANUEVA','ZAMBRANO',
  ],
  'BOYACÁ':[
    'TUNJA','ALMEIDA','AQUITANIA','ARCABUCO',
    'BELÉN','BERBEO','BETÉITIVA','BOAVITA','BOYACÁ','BRICEÑO','BUENAVISTA','BUENAVISTA',
    'CALDAS','CAMPOHERMOSO','CERINZA','CHINAVITA','CHIQUINQUIRÁ','CHISCAS','CHITA','CHITARAQUE',
    'CHIVATÁ','CIÉNEGA','CÓMBITA','COPER','CORRALES','COVARACHÍA','CUBARÁ','CUCAITA','CHÍQUIZA',
    'CHIVOR','DUITAMA','EL COCUY','EL ESPINO','FIRAVITOBA','FLORESTA','GACHANTIVÁ','GÁMEZA',
    'GARAGOA','GUACAMAYAS','GUATEQUE','GUAYATÁ','GÜICÁN DE LA SIERRA','IZA','JENESANO','JERICÓ',
    'LABRANZAGRANDE','LA CAPILLA','LA VICTORIA','LA UVITA','VILLA DE LEYVA','MACANAL','MARIPÍ',
    'MIRAFLORES','MONGUA','MONGUÍ','MONIQUIRÁ','MUZO','NOBSA','NUEVO COLÓN','OICATÁ','OTANCHE',
    'PACHAVITA','PÁEZ','PAIPA','PAJARITO','PANQUEBA','PAUNA','PAYA','PAZ DE RÍO','PESCA','PISBA',
    'PUERTO BOYACÁ','QUÍPAMA','RAMIRIQUÍ','RÁQUIRA','RONDÓN','SABOYÁ','SÁCHICA','SAMACÁ','SAN EDUARDO',
    'SAN JOSÉ DE PARE','SAN LUIS DE GACENO','SAN MATEO','SAN MIGUEL DE SEMA','SANTANA','SANTA MARÍA',
    'SANTA ROSA DE VITERBO','SANTA SOFÍA','SATIVANORTE','SATIVASUR','SIACHOQUE','SOATÁ','SOCHA','SOGAMOSO',
    'SOMONDOCO','SORA','SOTAQUIRÁ','SORACÁ','SUTAMARCHÁN','SUTATENZA','TASCO','TASCO','TIBANÁ','TIBASOSA',
    'TINJACÁ','TIPACOQUE','TOCA','TOGÜÍ','TÓPAGA','TOTA','TUNUNGUÁ','TURMEQUÉ','TUTA','TUTAZÁ','ÚMBITA','VENTAQUEMADA',
    'VIRACACHÁ','ZETAQUIRA',
  ],
  'CALDAS':[
    'MANIZALES','AGUADAS','ANSERMA','ARANZAZU','BELALCÁZAR','CHINCHINÁ','FILADELFIA',
    'LA DORADA','MANZANARES','MARMATO','MARQUETALIA','MARULANDA','NEIRA','NORCASIA',
    'PÁCORA','PALESTINA','PENSILVANIA','RIOSUCIO','RISARALDA','SALAMINA','SAMANÁ',
    'SAN JOSÉ','SUPÍA','VICTORIA','VILLAMARÍA','VITERBO',
  ],
  'CAQUETÁ':[
    'FLORENCIA','ALBANIA','BELÉN DE LOS ANDAQUÍES','CARTAGENA DEL CHAIRÁ','CURILLO',
    'EL DONCELLO','EL PAUJÍL','LA MONTAÑITA','MILÁN',
    'MORELIA','PUERTO RICO','SAN JOSÉ DEL FRAGUA',
    'SAN VICENTE DEL CAGUÁN','SOLANO','VALPARAÍSO',
  ],
  'CAUCA':[
    'POPAYÁN','ALMAGUER','ARGELIA','BALBOA','BOLÍVAR','BUENOS AIRES','CAJIBÍO','CALDONO',
    'CALOTO','EL TAMBO','FLORENCIA','GUACHENÉ','GUAPI','INZÁ','JAMBALÓ','LA SIERRA','LA VEGA',
    'LÓPEZ DE MICAY','MERCADERES','MIRANDA','MORALES','PADILLA','PÁEZ','PATÍA','PIAMONTE',
    'PIENDAMÓ - TUNÍA','PUERTO TEJADA','PURACÉ','ROSAS','SAN SEBASTIÁN','SANTANDER DE QUILICHAO','SANTA ROSA',
    'SILVIA','SOTARÁ - PAISPAMBA','SUÁREZ','SUCRE','TIMBÍO','TIMBIQUÍ','TORIBÍO','TOTORÓ','VILLA RICA',
  ],
  'CESAR':[
    'VALLEDUPAR','AGUACHICA','AGUSTÍN CODAZZI','ASTREA','BECERRIL','BOSCONIA','CHIMICHAGUA',
    'CURUMANÍ','EL COPEY','EL PASO','GAMARRA','GONZÁLEZ','LA GLORIA','LA JAGUA DE IBIRICO',
    'MANAURE BALCÓN DEL CESAR','PAILITAS','PELAYA','PUEBLO BELLO','RÍO DE ORO','LA PAZ','SAN ALBERTO','SAN DIEGO',
    'SAN DIEGO','TAMALAMEQUE',
  ],
  'CÓRDOBA:':[
    'MONTERÍA','AYAPEL','BUENAVISTA','CANALETE','CERETÉ','CHIMÁ','CHINÚ','CIÉNAGA DE ORO',
    'COTORRA','LA APARTADA','LORICA','LOS CÓRDOBAS','MOMIL','MONTELÍBANO','MOÑITOS','PLANETA RICA',
    'PUEBLO NUEVO','PUERTO ESCONDIDO','PUERTO LIBERTADOR','PURÍSIMA DE LA CONCEPCIÓN',
    'SAHAGÚN','SAN ANDRÉS DE SOTAVENTO','SAN ANTERO','SAN BERNARDO DEL VIENTO','SAN CARLOS',
    'SAN JOSÉ DE URÉ','SAN PELAYO','TIERRALTA','TUCHÍN','VALENCIA',
  ],
  'CUNDINAMARCA:':[
    'AGUA DE DIOS','ALBÁN','ANAPOIMA','ANOLAIMA','ARBELÁEZ','BELTRÁN','BITUIMA','BOJACÁ','CABRERA','CACHIPAY',
    'CAJICÁ','CAPARRAPÍ','CÁQUEZA','CARMEN DE CARUPA','CHAGUANÍ','CHÍA','CHIPAQUE','CHOACHÍ','CHOCONTÁ',
    'COGUA','COTA','CUCUNUBÁ','EL COLEGIO','EL PEÑÓN','EL ROSAL','FACATATIVÁ','FÓMEQUE','FOSCA',
    'FUNZA','FUSAGASUGÁ','GACHALÁ','GACHANCIPÁ','GACHETÁ','GAMA','GIRARDOT','GRANADA','GUACHETÁ',
    'GUADUAS','GUASCA','GUATAQUÍ','GUATAVITA','GUAYABAL DE SÍQUIMA','GUAYABETAL','GUTIÉRREZ','JERUSALÉN','JUNÍN',
    'LA CALERA','LA MESA','LA PALMA','LA PEÑA','LA VEGA','LENGUAZAQUE','MACHETÁ','MADRID','MANTA',
    'MEDINA','MOSQUERA','NARIÑO','NEMOCÓN','NILO','NIMAIMA','NOCAIMA','VENECIA','PACHO','PAIME','PANDI',
    'PARATEBUENO','PASCA','PUERTO SALGAR','PULÍ','QUEBRADANEGRA','QUETAME','QUIPILE','APULO','RICAURTE','SAN ANTONIO DEL TEQUENDAMA',
    'SAN BERNARDO','SAN CAYETANO','SAN FRANCISCO','SAN JUAN DE RIOSECO','SASAIMA','SESQUILÉ','SIBATÉ','SILVANIA','SIMIJACA',
    'SOACHA','SOPÓ','SUBACHOQUE','SUESCA','SUPATÁ','SUSA','SUTATAUSA','TABIO','TAUSA','TENA',
    'TENJO','TIBACUY','TIBIRITA','TOCAIMA','TOCANCIPÁ','TOPAIPÍ','UBALÁ','UBAQUE','VILLA DE SAN DIEGO DE UBATÉ',
    'UNE','ÚTICA','VERGARA','VIANÍ','VILLAGÓMEZ','VILLAPINZÓN','VILLETA','VIOTÁ','YACOPÍ','ZIPACÓN',
    'ZIPAQUIRÁ',
  ],
  'CHOCÓ:':[
    'QUIBDÓ','ACANDÍ','ALTO BAUDÓ','ATRATO','BAGADÓ','BAHÍA SOLANO','BAJO BAUDÓ','BOJAYÁ','EL CANTÓN DEL SAN PABLO'
    'CARMEN DEL DARIÉN','CÉRTEGUI','CONDOTO','EL CARMEN DE ATRATO','ISTMINA','JURADÓ','LLORÓ','MEDIO ATRATO','MEDIO BAUDÓ',
    'MEDIO SAN JUAN','NÓVITA','NUQUÍ','RÍO IRÓ','RÍO QUITO','RIOSUCIO','SAN JOSÉ DEL PALMAR','SIPÍ','TADÓ',
    'UNGUÍA','UNIÓN PANAMERICANA'
    ,
  ],
  'HUILA:':[
    'NEIVA','ACEVEDO','AIPE','ALGECIRAS','ALTAMIRA','BARAYA','CAMPOALEGRE','COLOMBIA',
    'ELÍAS','GARZÓN','GIGANTE','GUADALUPE','HOBO','ÍQUIRA','ISNOS','LA ARGENTINA',
    'LA PLATA','NÁTAGA','OPORAPA','PAICOL','PALERMO','PALESTINA','PITAL','PITALITO',
    'RIVERA','SALADOBLANCO','SAN AGUSTÍN','SANTA MARÍA','SUAZA','TARQUI','TESALIA',
    'TELLO','TERUEL','TIMANÁ','VILLAVIEJA','YAGUARÁ',
  ],
  'LA GUAJIRA':[
    'RIOHACHA','ALBANIA','BARRANCAS','DIBULLA','DISTRACCIÓN','EL MOLINO','FONSECA','HATONUEVO','LA JAGUA DEL PILAR',
    'MAICAO','MANAURE','SAN JUAN DEL CESAR','URIBIA','URUMITA','VILLANUEVA',
    
  ],
  'MAGDALENA':[
    'SANTA MARTA','ALGARROBO','ARACATACA','ARIGUANÍ','CERRO DE SAN ANTONIO','CHIVOLO','CIÉNAGA','CONCORDIA','EL BANCO',
    'EL PIÑÓN','EL RETÉN','FUNDACIÓN','GUAMAL','NUEVA GRANADA','PEDRAZA','PIJIÑO DEL CARMEN','PIVIJAY','PLATO',
    'PUEBLOVIEJO','REMOLINO','SABANAS DE SAN ÁNGEL','SALAMINA','SAN SEBASTIÁN DE BUENAVISTA','SAN ZENÓN','SANTA ANA',
    'SANTA BÁRBARA DE PINTO','SITIONUEVO','ZAPAYÁN','ZONA BANANERA',

  ],
  'META':[
    'VILLAVICENCIO','ACACÍAS','BARRANCA DE UPÍA','CABUYARO','CASTILLA LA NUEVA','CUBARRAL','CUMARAL',
    'EL CALVARIO','EL CASTILLO','EL DORADO','FUENTE DE ORO','GRANADA','GUAMAL','MAPIRIPÁN',
    'MESETAS','LA MACARENA','URIBE','LEJANÍAS','PUERTO CONCORDIA','PUERTO GAITÁN','PUERTO LÓPEZ',
    'PUERTO LLERAS','PUERTO RICO','RESTREPO','SAN CARLOS DE GUAROA','SAN JUANITO','SAN MARTÍN','VISTAHERMOSA',
  ],
  'NARIÑO':[
    'PASTO','ALBÁN','ALDANA','ANCUYA','ARBOLEDA','BARBACOAS','BELÉN','BUESACO','COLÓN',
    'CONSACÁ','CONTADERO','CÓRDOBA','CUASPUD CARLOSAMA','CUMBAL','CUMBITARA','CHACHAGÜÍ',
    'EL CHARCO','EL PEÑOL','EL ROSARIO','EL TABLÓN DE GÓMEZ','EL TAMBO','FUNES','GUACHUCAL','GUAITARILLA','GUALMATÁN',
    'ILES','IMUÉS','IPIALES','LA CRUZ','LA FLORIDA','LA LLANADA','LA TOLA','LA UNIÓN','LEIVA',
    'LINARES','LOS ANDES','MAGÜÍ','MALLAMA','MOSQUERA','NARIÑO','OLAYA HERRERA','OSPINA','FRANCISCO PIZARRO',
    'POLICARPA','POTOSÍ','PROVIDENCIA','PUERRES','PUPIALES','RICAURTE','ROBERTO PAYÁN','SAMANIEGO','SANDONÁ',
    'SAN BERNARDO','SAN LORENZO','SAN PABLO','SAN PEDRO DE CARTAGO','SANTA BÁRBARA','SANTACRUZ','SAPUYES','TAMINANGO',
    'TANGUA','SAN ANDRÉS DE TUMACO','TÚQUERRES','YACUANQUER',
    
  ],
  'NORTE DE SANTANDER':[
    'SAN JOSÉ DE CÚCUTA','ÁBREGO','ARBOLEDAS','BOCHALEMA','BUCARASICA','CÁCOTA','CÁCHIRA','CHINÁCOTA','CHITAGÁ',
    'CONVENCIÓN','CUCUTILLA','DURANIA','EL CARMEN','EL TARRA','EL ZULIA','GRAMALOTE','HACARÍ','HERRÁN',
    'LABATECA','LA ESPERANZA','LA PLAYA','LOS PATIOS','LOURDES','MUTISCUA','OCAÑA','PAMPLONA','PAMPLONITA',
    'PUERTO SANTANDER','RAGONVALIA','SALAZAR','SAN CALIXTO','SAN CAYETANO','SANTIAGO','SARDINATA','SILOS','TEORAMA',
    'TIBÚ','TOLEDO','VILLA CARO','VILLA DEL ROSARIO',
  ],
  'QUINDIO':[
    'ARMENIA','BUENAVISTA','CALARCÁ','CIRCASIA','CÓRDOBA','FILANDIA','GÉNOVA','LA TEBAIDA','MONTENEGRO',
    'PIJAO','QUIMBAYA','SALENTO',
  ],
  'RISARALDA':[
    'PEREIRA','APÍA','BALBOA','BELÉN DE UMBRÍA','DOSQUEBRADAS','GUÁTICA',
    'LA CELIA','LA VIRGINIA','MARSELLA','MISTRATÓ','PUEBLO RICO','QUINCHÍA','SANTA ROSA DE CABAL',
    'SANTUARIO',
  ],
  'SANTANDER':[
    'BUCARAMANGA','AGUADA','ALBANIA','ARATOCA','BARICHARA','BARRANCABERMEJA','BETULIA','BOLÍVAR','CALIFORNIA',
    'CAPITANEJO','CARCASÍ','CARCASÍ','CERRITO','CHARALÁ','CHARTA','CHIMA','CHIPATÁ','CIMITARRA',
    'CONCEPCIÓN','CONFINES','CONTRATACIÓN','COROMORO','CURITÍ','EL CARMEN DE CHUCURI','EL GUACAMAYO','EL PEÑÓN','EL PLAYÓN',
    'ENCINO','FLORIÁN','FLORIDABLANCA','GALÁN','GÁMBITA','GIRÓN','GUACA','GUADALUPE','GUAVATÁ',
    'GÜEPSA','HATO','JESÚS MARÍA','JORDÁN','LA BELLEZA','LANDÁZURI','LA PAZ','LEBRIJA','LOS SANTOS',
    'MACARAVITA','MÁLAGA','MATANZA','MOGOTES','MOLAGAVITA','OCAMONTE','OIBA','ONZAGA','PALMAS DEL SOCORRO',
    'PÁRAMO','PIEDECUESTA','PINCHOTE','PUENTE NACIONAL','PUERTO PARRA','PUERTO WILCHES','RIONEGRO','SABANA DE TORRES',
    'SAN ANDRÉS','SAN GIL','SAN JOAQUÍN','SAN JOSÉ DE MIRANDA','SAN MIGUEL','SAN VICENTE DE CHUCURÍ','SANTA BÁRBARA',
    'SANTA HELENA DEL OPÓN','SIMACOTA','SOCORRO','SUAITA','SUCRE','SURATÁ','TONA','VALLE DE SAN JOSÉ','VÉLEZ',
    'VETAS','VILLANUEVA','ZAPATOCA',
  ],
  'SUCRE':[
    'SINCELEJO','SINCELEJO','CAIMITO','COLOSÓ','COROZAL','COVEÑAS','CHALÁN','EL ROBLE','GALERAS',
    'LA UNIÓN','LOS PALMITOS','MAJAGUAL','MORROA','OVEJAS','PALMITO','SAMPUÉS','SAN BENITO ABAD','SAN MARCOS',
    'SAN ONOFRE','SAN PEDRO','SAN LUIS DE SINCÉ','SUCRE','SANTIAGO DE TOLÚ'
  ],
  'TOLIMA':[
    'IBAGUÉ','ALPUJARRA','ALVARADO','AMBALEMA','ANZOÁTEGUI','ARMERO','ATACO',
    'CAJAMARCA','CARMEN DE APICALÁ','CASABIANCA','CHAPARRAL','COELLO','COYAIMA',
    'CUNDAY','DOLORES','ESPINAL','FALAN','FLANDES','FRESNO','GUAMO','HERVEO','HONDA',
    'ICONONZO','LÉRIDA','LÍBANO','SAN SEBASTIÁN DE MARIQUITA','MELGAR','MURILLO','NATAGAIMA',
    'ORTEGA','PALOCABILDO','PIEDRAS','PLANADAS','PRADO','PURIFICACIÓN','RIOBLANCO','RONCESVALLES',
    'ROVIRA','SALDAÑA','SAN ANTONIO','SAN LUIS','SANTA ISABEL','SUÁREZ','VALLE DE SAN JUAN','VENADILLO',
    'VILLAHERMOSA','VILLARRICA',
  ],
  'VALLE DEL CAUCA':[
    'CALI','ALCALÁ','ANSERMANUEVO','ARGELIA','BUENAVENTURA','GUADALAJARA DE BUGA','BUGALAGRANDE','CAICEDONIA',
    'CALIMA','CANDELARIA','CARTAGO','DAGUA','EL ÁGUILA','EL CAIRO','EL CERRITO','EL DOVIO',
    'FLORIDA','GINEBRA','GUACARÍ','JAMUNDÍ','LA CUMBRE','LA UNIÓN','LA VICTORIA','OBANDO',
    'PALMIRA','PRADERA','RESTREPO','RIOFRÍO','ROLDANILLO','SAN PEDRO','SEVILLA','TORO',
    'TRUJILLO','TULUÁ','ULLOA','VERSALLES','VIJES','YOTOCO','YUMBO','ZARZAL',
 
  ],
  'ARAUCA':[
    'ARAUCA','ARAUQUITA','CRAVO NORTE','FORTUL','PUERTO RONDÓN','SARAVENA','TAME'
  ],
  'CASANARE':[
    'YOPAL','AGUAZUL','HATO COROZAL','LA SALINA','MANÍ','MONTERREY','NUNCHÍA','OROCUÉ',
    'PAZ DE ARIPORO','PORE','RECETOR','SABANALARGA','SÁCAMA','SAN LUIS DE PALENQUE','TÁMARA','TAURAMENA',
    'TRINIDAD','VILLANUEVA',

  ],
  'PUTUMAYO':[
   'MOCOA','ORITO','PUERTO ASÍS','PUERTO CAICEDO','PUERTO GUZMÁN','PUERTO LEGUÍZAMO','SIBUNDOY','SAN FRANCISCO',
    'SAN MIGUEL','SANTIAGO','VALLE DEL GUAMUEZ','VILLAGARZÓN',

  ],
  'ARCHIPIÉLAGO DE SAN ANDRÉS':[
    'SAN ANDRÉS','PROVIDENCIA',
 
  ],
  'AMAZONAS':[
    'LETICIA','EL ENCANTO','LA CHORRERA','LA VICTORIA','MIRITÍ - PARANÁ','PUERTO ALEGRÍA','PUERTO ARICA','PUERTO NARIÑO',
    'PUERTO SANTANDER','TARAPACÁ',
  ],
  'GUAINÍA':[
  'INÍRIDA','BARRANCOMINAS','SAN FELIPE','PUERTO COLOMBIA','PUERTO COLOMBIA','LA GUADALUPE','CACAHUAL','PANA PANA',
  'MORICHAL',
   

  ],
  'GUAVIARE':[
    'SAN JOSÉ DEL GUAVIARE','CALAMAR','EL RETORNO','MIRAFLORES',
    
  ],
  'VAUPÉS':[
    'MITÚ','CARURÚ','PACOA','TARAIRA',
    'PAPUNAHUA','YAVARATÉ',
    
  ],
  'VICHADA':[
    'PUERTO CARREÑO','LA PRIMAVERA','SANTA ROSALÍA','CUMARIBO',
  ],

  };

}