/*
clase para manejar la lista de municipios, departamentos, veredas
*/

class PlacesListJson {

//lista de departamentos
static List<String> departments = [
  'ANTIOQUIA', 
  'ATLÁNTICO', 
  'BOGOTÁ, D,C',
  'BOLÍVAR',
  'BOYACÁ',
  'CALDAS',
  'CAQUETÁ',
  'CAUCA',
  'CESAR',
  'CÓRDOBA',
  'CUNDINAMARCA',
  'CHOCÓ',
  'HUILA',
  'LA GUAJIRA',
  'MAGDALENA',
  'META',
  'NARIÑO',
  'NORTE DE SANTANDER',
  'QUINDIO',
  'RISARALDA',
  'SANTANDER',
  'SUCRE',
  'TOLIMA',
  'VALLE DEL CAUCA',
  'ARAUCA',
  'CASANARE',
  'PUTUMAYO',
  'ARCHIPIÉLAGO DE SAN ANDRÉS',
  'AMAZONAS',
  'GUAINÍA',
  'GUAVIARE',
  'VAUPÉS',
  'VICHADA',
  ];



/*lista de municipios*/
 static Map<String, List<String>> municipalitiesByDepartment = {

  'ANTIOQUIA':[
    'MEDELLÍN','ABEJORRAL','ABRIAQUÍ','ALEJANDRÍA','AMAGÁ','AMALFI','ANDES','ANGELÓPOLIS',
    'ANGOSTURA','ANORÍ','SANTA FÉ DE ANTIOQUIA','ANZÁ','APARTADÓ','ARBOLETES','ARGELIA',
    'BARBOSA','BELMIRA','BELLO','BETANIA','BETULIA','CIUDAD BOLÍVAR','BRICEÑO','BURITICÁ','CÁCERES',
    'CALDAS','CAMPAMENTO','CAÑASGORDAS','CARACOLÍ','CARAMANTA','CAREPA','EL CARMEN DE VIBORAL',
    'CAROLINA','CAUCASIA','CHIGORODÓ','COCORNÁ','CONCEPCIÓN','CONCORDIA','COPACABANA','DABEIBA',
    'DONMATÍAS','EBÉJICO','EL BAGRE','ENTRERRÍOS','ENVIGADO','FREDONIA','FRONTINO','GIRALDO','GIRARDOTA',
    'GÓMEZ PLATA','GRANADA','GUADALUPE','GUARNE','GUATAPÉ','HELICONIA','HISPANIA','ITAGÜÍ','ITUANGO','JARDÍN',
    'JERICÓ','LA CEJA','LA ESTRELLA','LA UNIÓN','LIBORINA','MACEO','MARINILLA','MONTEBELLO','MURINDÓ',
    'MUTATÁ','NARIÑO','NECOCLÍ','NECHÍ','OLAYA','PEÑOL','PEÑOL','PUEBLORRICO','PUEBLORRICO','PUERTO BERRÍO',
    'PUERTO NARE','PUERTO TRIUNFO','REMEDIOS','RETIRO','RIONEGRO','SABANALARGA','SABANETA','SALGAR','SAN ANDRÉS DE CUERQUÍA',
    'SAN CARLOS','SAN FRANCISCO','SAN JOSÉ DE LA MONTAÑA','SAN JUAN DE URABÁ','SAN LUIS',
    'SAN PEDRO DE LOS MILAGROS','SAN PEDRO DE URABÁ',
    'SAN RAFAEL','SAN ROQUE','SAN VICENTE FERRER','SANTA BÁRBARA','SANTA ROSA DE OSOS',
    'SANTO DOMINGO','EL SANTUARIO','SEGOVIA','SONSÓN',
    'SOPETRÁN','TÁMESIS','TARAZÁ','TARSO','TITIRIBÍ','TOLEDO','TURBO','URAMITA','URRAO',
    'VALDIVIA','VALPARAÍSO','VEGACHÍ','VIGÍA DEL FUERTE','YALÍ','YARUMAL','YOLOMBÓ','YONDÓ','ZARAGOZA',
    ], 
  'ATLÁNTICO':[
    'BARRANQUILLA','BARANOA','CAMPO DE LA CRUZ','CANDELARIA','GALAPA','JUAN DE ACOSTA',
    'LURUACO','MALAMBO','MANATÍ','PALMAR DE VARELA','PIOJÓ','POLONUEVO','PONEDERA','PUERTO COLOMBIA',
    'REPELÓN','SABANAGRANDE','SABANALARGA','SANTA LUCÍA','SANTO TOMÁS','SOLEDAD','SUAN','TUBARÁ','USIACURÍ'
  ], 
  'BOGOTÁ, D,C':[
    'BOGOTÁ, D.C.'
  ],
  'BOLÍVAR':[
    'CARTAGENA DE INDIAS','ACHÍ','ALTOS DEL ROSARIO','ARENAL','ARJONA','ARROYOHONDO',
    'BARRANCO DE LOBA','CALAMAR','CANTAGALLO','CICUCO','CÓRDOBA','CLEMENCIA',
    'EL CARMEN DE BOLÍVAR','EL GUAMO','EL PEÑÓN',
    'HATILLO DE LOBA','MAGANGUÉ','MAHATES','MARGARITA',
    'MARÍA LA BAJA','MONTECRISTO','MOMPÓS','NOROSÍ','PINILLOS','REGIDOR',
    'RÍO VIEJO','SAN CRISTÓBAL','SAN FERNANDO','SAN JACINTO','SAN JACINTO DEL CAUCA',
    'SAN PABLO','SANTA CATALINA','SANTA ROSA','SANTA ROSA DEL SUR','SIMITÍ','SOPLAVIENTO',
    'TIQUISIO','TURBACO','TURBANÁ','VILLANUEVA','ZAMBRANO',
  ],
  'BOYACÁ':[
    'TUNJA','ALMEIDA','AQUITANIA','ARCABUCO',
    'BELÉN','BERBEO','BETÉITIVA','BOAVITA','BOYACÁ','BRICEÑO','BUENAVISTA','BUENAVISTA',
    'CALDAS','CAMPOHERMOSO','CERINZA','CHINAVITA','CHIQUINQUIRÁ','CHISCAS','CHITA','CHITARAQUE',
    'CHIVATÁ','CIÉNEGA','CÓMBITA','COPER','CORRALES','COVARACHÍA','CUBARÁ','CUCAITA','CHÍQUIZA',
    'CHIVOR','DUITAMA','EL COCUY','EL ESPINO','FIRAVITOBA','FLORESTA','GACHANTIVÁ','GÁMEZA',
    'GARAGOA','GUACAMAYAS','GUATEQUE','GUAYATÁ','GÜICÁN DE LA SIERRA','IZA','JENESANO','JERICÓ',
    'LABRANZAGRANDE','LA CAPILLA','LA VICTORIA','LA UVITA','VILLA DE LEYVA','MACANAL','MARIPÍ','MIRAFLORES','MONGUA','MONGUÍ','MONIQUIRÁ','MUZO','NOBSA','NUEVO COLÓN','OICATÁ','','','','','',
    '','','','','','','','','','','','','','','','','','','','','','','',
  ],
  'CALDAS':[],
  'CAQUETÁ':[],
  'CAUCA':[],
  'CESAR':[],
  'CÓRDOBA:':[],
  'CUNDINAMARCA:':[],
  'CHOCÓ:':[],
  'HUILA:':[],
  'LA GUAJIRA':[],
  'MAGDALENA':[],
  'META':[],
  'NARIÑO':[],
  'NORTE DE SANTANDER':[],
  'QUINDIO':[],
  'RISARALDA':[],
  'SANTANDER':[],
  'SUCRE':[],
  'TOLIMA':[],
  'VALLE DEL CAUCA':[],
  'ARAUCA':[],
  'CASANARE':[],
  'PUTUMAYO':[],
  'ARCHIPIÉLAGO DE SAN ANDRÉS':[],
  'AMAZONAS':[],
  'GUAINÍA':[],
  'GUAVIARE':[],
  'VAUPÉS':[],
  'VICHADA':[],
  };

}